const fs = require('fs');
const path = require('path');
const dir = 'supabase/migrations';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.sql')).sort();
let out = '-- ==========================================\n';
out += '-- COMPILED PRODUCTION DEPLOY SCRIPT\n';
out += '-- Generated by Antigravity\n';
out += '-- ==========================================\n\n';

for(const f of files) {
  out += '-- \n-- [START] ' + f + '\n-- \n';
  let content = fs.readFileSync(path.join(dir, f), 'utf-8');
  
  // Inject DROP POLICY IF EXISTS before CREATE POLICY
  // Handle both CREATE POLICY and CREATE POLICY IF NOT EXISTS (if any)
  content = content.replace(/CREATE\s+POLICY\s+(.+?)\s+ON\s+([a-zA-Z0-9_.]+)/ig, (match, p1, p2) => {
    return 'DROP POLICY IF EXISTS ' + p1 + ' ON ' + p2 + ';\n' + match;
  });

  out += content;
  out += '\n\n-- \n-- [END] ' + f + '\n-- \n\n';
}

fs.mkdirSync('supabase/dist', {recursive: true});
fs.writeFileSync('supabase/dist/production_deploy.sql', out);
console.log('Regenerated supabase/dist/production_deploy.sql with DROP POLICY IF EXISTS successfully.');
