import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.coerce.number().default(3000),
  HOST: z.string().default('0.0.0.0'),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),

  SUNAT_ENV: z.enum(['beta', 'production']).default('beta'),
  SUNAT_BETA_URL: z.string().url().default('https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService'),
  SUNAT_PRODUCTION_URL: z.string().url().default('https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService'),

  SUNAT_RUC: z.string().length(11),
  SUNAT_USUARIO_SOL: z.string().min(1),
  SUNAT_CLAVE_SOL: z.string().min(1),

  SUNAT_PFX_BASE64: z.string().optional(),
  SUNAT_PFX_PASSWORD: z.string().optional(),
  SUNAT_PRIVATE_KEY_PEM: z.string().optional(),
  SUNAT_CERTIFICATE_PEM: z.string().optional(),

  XML_ENCODING: z.enum(['UTF-8', 'ISO-8859-1']).default('UTF-8'),
  ZIP_COMMENT: z.string().default('Generated by SUNAT Wrapper v1.0.0'),

  RATE_LIMIT_MAX: z.coerce.number().default(100),
  RATE_LIMIT_WINDOW_MS: z.coerce.number().default(60000),

  SUNAT_TIMEOUT_MS: z.coerce.number().default(30000),
});

export type EnvConfig = z.infer<typeof envSchema>;

let cachedConfig: EnvConfig | null = null;

export function loadConfig(): EnvConfig {
  if (cachedConfig) return cachedConfig;

  const result = envSchema.safeParse(process.env);
  if (!result.success) {
    console.error('❌ Invalid environment configuration:');
    console.error(result.error.flatten().fieldErrors);
    process.exit(1);
  }

  cachedConfig = result.data;
  return cachedConfig;
}

export function getConfig(): EnvConfig {
  if (!cachedConfig) {
    return loadConfig();
  }
  return cachedConfig;
}

export function getSunatEndpoint(): string {
  const config = getConfig();
  return config.SUNAT_ENV === 'production' 
    ? config.SUNAT_PRODUCTION_URL 
    : config.SUNAT_BETA_URL;
}

export function getSunatUsername(): string {
  const config = getConfig();
  return `${config.SUNAT_RUC}${config.SUNAT_USUARIO_SOL}`;
}