/**
 * ZIP Packaging Utility
 * Empaqueta documentos XML firmados en archivos ZIP según especificaciones SUNAT
 * Nomenclatura: [RUC]-[TIPO_COMPROBANTE]-[SERIE]-[CORRELATIVO].zip
 * El ZIP debe contener exactamente un archivo XML
 */

import JSZip from 'jszip';
import { SignedDocument } from '@/types/sunat';

export interface ZipOptions {
  comment?: string;
  compression?: 'STORE' | 'DEFLATE';
  compressionLevel?: number; // 1-9 para DEFLATE
}

export interface ZipResult {
  zipBase64: string;
  zipBuffer: Buffer;
  fileName: string;
  size: number;
  crc32: number;
}

/**
 * Servicio para crear y manipular archivos ZIP para SUNAT
 */
export class ZipService {
  private readonly defaultOptions: Required<ZipOptions> = {
    comment: 'Generated by SUNAT Wrapper v1.0.0',
    compression: 'DEFLATE',
    compressionLevel: 6,
  };

  /**
   * Crea un archivo ZIP con un solo archivo XML (estándar SUNAT)
   */
  async createZip(
    fileName: string,
    xmlContent: string,
    options: ZipOptions = {}
  ): Promise<ZipResult> {
    const opts = { ...this.defaultOptions, ...options };
    const zip = new JSZip();

    // Agregar archivo XML al ZIP
    zip.file(fileName, xmlContent, {
      compression: opts.compression === 'DEFLATE' ? 'DEFLATE' : 'STORE',
      compressionOptions: {
        level: opts.compressionLevel,
      },
    });

    // Generar buffer
    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: opts.compression === 'DEFLATE' ? 'DEFLATE' : 'STORE',
      compressionOptions: {
        level: opts.compressionLevel,
      },
      comment: opts.comment,
    }) as Buffer;

    // Calcular CRC32 del archivo XML dentro del ZIP
    const zipFile = zip.file(fileName);
    const crc32 = zipFile ? (zipFile as any).crc32 || 0 : 0;

    return {
      zipBase64: zipBuffer.toString('base64'),
      zipBuffer,
      fileName: fileName.replace('.xml', '.zip'),
      size: zipBuffer.length,
      crc32,
    };
  }

  /**
   * Crea ZIP desde un SignedDocument (ya tiene xml y fileName)
   */
  async createZipFromSigned(doc: SignedDocument, options: ZipOptions = {}): Promise<ZipResult> {
    return this.createZip(doc.fileName, doc.xml, options);
  }

  /**
   * Crea un ZIP con múltiples XMLs (para sendPack - máximo 500)
   * SUNAT requiere que cada XML esté en el raíz del ZIP (sin carpetas)
   */
  async createMultiZip(
    documents: Array<{ fileName: string; xmlContent: string }>,
    options: ZipOptions = {}
  ): Promise<ZipResult> {
    if (documents.length > 500) {
      throw new Error('SUNAT sendPack permite máximo 500 comprobantes por ZIP');
    }

    const opts = { ...this.defaultOptions, ...options };
    const zip = new JSZip();

    documents.forEach(doc => {
      zip.file(doc.fileName, doc.xmlContent, {
        compression: opts.compression === 'DEFLATE' ? 'DEFLATE' : 'STORE',
        compressionOptions: { level: opts.compressionLevel },
      });
    });

    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: opts.compression === 'DEFLATE' ? 'DEFLATE' : 'STORE',
      compressionOptions: { level: opts.compressionLevel },
      comment: opts.comment,
    }) as Buffer;

    return {
      zipBase64: zipBuffer.toString('base64'),
      zipBuffer,
      fileName: `lote-${Date.now()}.zip`,
      size: zipBuffer.length,
      crc32: 0, // No aplica para múltiples archivos
    };
  }

  /**
   * Extrae un archivo XML de un ZIP (para getStatusCdr)
   */
  async extractXmlFromZip(zipBase64: string, fileName?: string): Promise<{
    xml: string;
    fileName: string;
  }> {
    const zipBuffer = Buffer.from(zipBase64, 'base64');
    const zip = await JSZip.loadAsync(zipBuffer);

    let targetFile: JSZip.JSZipObject | null = null;

    if (fileName) {
      targetFile = zip.file(fileName) || null;
    } else {
      // Buscar el primer archivo .xml
      const files = Object.values(zip.files);
      targetFile = files.find(f => f.name.endsWith('.xml') && !f.dir) || null;
    }

    if (!targetFile) {
      throw new Error('No XML file found in ZIP');
    }

    const xml = await targetFile.async('text');
    return { xml, fileName: targetFile.name };
  }

  /**
   * Valida que un ZIP cumple con los requisitos SUNAT
   */
  async validateSunatZip(zipBase64: string): Promise<{
    valid: boolean;
    errors: string[];
    fileCount: number;
    xmlFiles: string[];
  }> {
    const errors: string[] = [];
    const xmlFiles: string[] = [];

    try {
      const zipBuffer = Buffer.from(zipBase64, 'base64');
      const zip = await JSZip.loadAsync(zipBuffer);

      const files = Object.values(zip.files).filter(f => !f.dir);
      
      if (files.length === 0) {
        errors.push('ZIP está vacío');
      }

      if (files.length > 1) {
        errors.push(`ZIP contiene ${files.length} archivos, SUNAT requiere exactamente 1 (para sendBill) o hasta 500 (para sendPack)`);
      }

      for (const file of files) {
        if (!file.name.endsWith('.xml')) {
          errors.push(`Archivo no es XML: ${file.name}`);
        } else {
          xmlFiles.push(file.name);
          
          // Validar nomenclatura SUNAT: RUC-TIPO-SERIE-CORRELATIVO.xml
          const namePattern = /^\d{11}-\d{2}-[A-Z0-9]{1,4}-\d{1,8}\.xml$/;
          if (!namePattern.test(file.name)) {
            errors.push(`Nomenclatura inválida (esperado: RUC-TIPO-SERIE-CORRELATIVO.xml): ${file.name}`);
          }
        }
      }

      return {
        valid: errors.length === 0,
        errors,
        fileCount: files.length,
        xmlFiles,
      };
    } catch (error) {
      return {
        valid: false,
        errors: [`ZIP inválido: ${error instanceof Error ? error.message : 'Error desconocido'}`],
        fileCount: 0,
        xmlFiles: [],
      };
    }
  }

  /**
   * Genera nombre de archivo según estándar SUNAT
   * Formato: [RUC]-[TIPO_COMPROBANTE]-[SERIE]-[CORRELATIVO].xml
   */
  static generateFileName(
    ruc: string,
    documentType: string,
    series: string,
    correlative: number
  ): string {
    const paddedCorrelative = correlative.toString().padStart(8, '0');
    return `${ruc}-${documentType}-${series}-${paddedCorrelative}.xml`;
  }

  /**
   * Parsea nombre de archivo SUNAT
   */
  static parseFileName(fileName: string): {
    ruc: string;
    documentType: string;
    series: string;
    correlative: number;
  } | null {
    const match = fileName.match(/^(\d{11})-(\d{2})-([A-Z0-9]{1,4})-(\d{1,8})\.xml$/);
    if (!match) return null;

    return {
      ruc: match[1],
      documentType: match[2],
      series: match[3],
      correlative: parseInt(match[4], 10),
    };
  }
}

export const zipService = new ZipService();